global:
  image: {}
  connectors:
    image: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.global.connectors.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)


image: 
  name: "magda-csw-connector"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: ghcr.io/magda-io
  pullPolicy: IfNotPresent
  imagePullSecret: false

resources:
  requests:
    cpu: 50m
    memory: 30Mi
  limits:
    cpu: 100m

defaultSettings:
  includeInitialJobs: false
  includeCronJobs: true

# Chart level .Values.includeInitialJobs is higher priority than 
# .Values.global.includeInitialJobs
# The value of includeInitialJobs or includeCronJobs is determined by:
# - .Values.includeInitialJobs if its value is set
# - Then .Values.global.includeInitialJobs if its value is set
# - Then .Values.defaultSettings.includeInitialJobs
# By default, .Values.includeInitialJobs is not set. 
# Therefore, if .Values.global.includeInitialJobs is not set, .Values.defaultSettings.includeInitialJobs will be used.

#includeInitialJobs: false
#includeCronJobs: true

defaultTenantId: 0

config:
  ## Unique id to identify this connector and records that are harvested from it
  id: default-csw-connector

  # -- (string) Friendly readable name. Compulsory.
  name:
  
  # -- (string) The base URL of the place to source data from. Compulsory.
  sourceUrl: 
  
  # -- (int) When crawling through from beginning to end, how big should the individual requests be in records?
  pageSize: 100
  
  # -- Crontab schedule for how often this should happen.
  # @default -- "0 14 * * 6" i.e. 12am Sydney time on Sunday
  schedule:

  # -- Whether or not use POST request to call getRecords API
  usePostRequest: false

  # -- Whether or not to send basic auth header.
  basicAuthEnabled: false

  # -- basic auth username. You can also passing this value via secret.
  # To do so, set `basicAuthSecretName` to the secret name.
  basicAuthUsername:

  # -- basic auth password. You can also passing this value via secret.
  # To do so, set `basicAuthSecretName` to the secret name.
  basicAuthPassword:

  # -- You can set this value to supply basic auth username & password.
  # The secret must have two keys: `username` & `password`.
  basicAuthSecretName:

  # -- (string) Desired output schema to be requested from CSW service as URI
  # @default -- http://www.isotc211.org/2005/gmd
  outputSchema:

  # -- (string) Record type expected to be returned from CSW service as XML tag name
  # @default -- gmd:MD_Metadata
  typeNames: 
